# flask api for transportation (price, eta, co2) estimates
# run api_data.sh first to populate tmp-directory 
FROM python:3

ADD api.py /
ADD lane.py /

ADD tmp/ODMatrix2021_N2.csv /
ADD tmp/nuts-names-21.csv /
ADD tmp/nuts.csv /
ADD tmp/nuts3.json /
# ADD tmp/<models>

RUN pip install flask
RUN pip install flask_restful
RUN pip install flask-expects-json

EXPOSE 3333

CMD ["python", "./api.py"]

